#!/bin/bash
nsec=$(date +%N);sw=1;sec=$(date +%S);
nsec=`echo $nsec|sed 's/^0*//'`; #This is to avoid the `value too great` error.
while [ $sw -ne 0 ]
do
	if [ $sec -le 15 ]
	then
	val1=$((nsec+sec))
	sec=$((sec+15));
	fi
	if [ $sec -gt 15 ] && [ $sec -le 30 ]
	then
	val1=$((nsec-val1));
	sec=$((sec+15));
	fi
	if [ $sec -gt 30 ] && [ $sec -le 45 ]
	then
	val1=$((nsec*val1))
	sec=$((sec+15));
	fi
	if [ $sec -gt 45 ] && [ $sec -le 59 ]
	then
	val1=$((nsec/sec))
	sec=$((sec+15));
	fi
sw=$((sw-1));
done
if [ -z $1 ]
then
echo $val1;
fi
if [ $1 == '-h' 2>/dev/null ]
then
echo -e "\nGenerates random numeric values.\n";
fi
